DEVICE: "cuda"

DETECTION:
  WEIGHTS: "weights/dbnet_res50_20241024.pth"
  BACKBONE:
    NAME: "resnet50"
    DILATION: True

  DECODER:
    IN_CHANNELS: [256, 512, 1024, 2048]
    HIDDEN_DIM: 256
    ADAPTIVE: True
    SERIAL: False
    SMOOTH: False
    K: 50

  DATA:
    SHORTEST_SIZE: 768
    LIMIT_SIZE: 1920

  POST_PROCESS:
    MIN_SIZE: 2
    THRESH: 0.3
    BOX_THRESH: 0.5
    MAX_CANDIDATES: 1500
    UNCLIP_RATIO: 2.5

  VISUALIZE:
    COLOR: [0, 255, 0] #RGB
    HEATMAP: False

RECOGNITION:
  WEIGHTS: weights/checkpoint_4_79999.pth
  CHARSET: "resource/charset.txt"

  DATA:
    NUM_WORKERS: 4
    BATCH_SIZE: 128
    IMAGE_SIZE: [32, 800]

  MODEL:
    MAX_LEN: 100
    PATCH_SIZE: [8, 8]
    HIDDEN_DIM: 512
    ENC_NUM_HEADS: 8
    ENC_MLP_RATIO: 4
    ENC_DEPTH: 12
    DEC_NUM_HEADS: 8
    DEC_MLP_RATIO: 4
    DEC_DEPTH: 1
    DECODE_AR: True
    REFINE_ITERS: 1
    DROPOUT: 0.1

  VISUALIZE:
    FONT: resource/MPLUS1p-Medium.ttf
    COLOR: [0, 0, 255] #RGB
    FONT_SIZE: 12

  

