name: Python Lint

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - name: Install dependencies
        run: sudo apt install -y libopencv-dev poppler-utils
      - name: Install tox-uv
        run: uv tool install tox
      - name: Run linter
        run: tox -e lint
      - name: Run tests
        run:  tox r -e py39,py310,py311,py312
